// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"CC_AutoFullScreen","status":true,"description":"Start game in full screen mode.","parameters":{"default":"true","Scene_Options":"","optionCommandEnable":"true","textOptionCommand":"Full Screen"}},
{"name":"SNBR_SkipTitleScreen","status":true,"description":"Skip title screen, and go directly to New Game","parameters":{}}
];
